@echo off
echo Transformation de %1.xml en %3.fo par %2.xsl ...
java org.apache.xalan.xslt.Process -IN %1.xml -XSL %2.xsl -OUT %3.fo
echo Transformation de %3.fo en %3.pdf ...
java org.apache.fop.apps.Fop -fo %3.fo -pdf %3.pdf